include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - prefer_relative_imports
    - combinators_ordering
    - prefer_const_constructors