name: hotel_service
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.4.1
  auto_route: ^7.8.0
  bloc: ^8.1.1
  dio: ^5.1.2
  flutter_bloc: ^8.1.2
  flutter_slidable: ^3.0.1
  freezed_annotation: ^2.0.3
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  mockito: ^5.4.2
  mocktail: ^1.0.0
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  path: ^1.8.0
  overflow_view: ^0.3.1
  image_picker: ^1.0.4
  record: ^5.0.1
  audioplayers: ^5.2.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  freezed: ^2.4.5
  json_serializable: ^6.6.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/logo.png
