name: get_photos_from_device
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.get_photos_from_device
        pluginClass: GetPhotosFromDevicePlugin
      ios:
        pluginClass: GetPhotosFromDevicePlugin